export const facts = [
  "Sign language varies from country to country. Most of the country have their own sign language or share a certain sign language but, with a different dialect.",
  "ASL has its own vocabulary, grammar, word order and style and does not necessarily reflect English words. ASL originates from France, that’s why French Sign Language is very similar to ASL.",
  "There are 300 different sign languages with actually only 130 that are recognized worldwide. These variations include: Italian, Chinese, Japanese, German and Korean. Internationally, the most commonly used sign languages  are American Sign Language (ASL), British Sign Language (BSL) and French Sign Language (FSL).",
  "Sign Language developed naturally from interactions between people and was influenced by their age, gender, culture and more. There are about 6,000 different sign languages around the world.",
  "Through interactions with people around them, deaf babies explore the hand shapes and movements that make up signs by babbling with their hands. In the early developmental stages, deaf children often substitute easier handshapes for more difficult ones.",
  "Sign language is based on the idea that sight is the most useful tool a deaf person has to communicate and receive information. Sign language doesn’t only use signs to communicate. It uses facial expression, hand movement and position, gestures and body language to communicate.",
  "In the American Sign Language (ASL), the alphabets can be demonstrated using one hand. However, in German and British Sign Languages, two hands are used.",
  "Deaf people often use name signs to refer to people. These name signs are attributed to each person and doesn’t requires fingerspelling the entire name. When you meet a deaf person, it is a practice to tell them your name sign.",
  "“I love you” in ASL is the combination of signs for the letters I, L and Y.",
  "It’s easy to forget sign language as an actual language. People learn to sign in the same way they learn to speak. Also, different parts of your brain are used to speaking which is pretty cool.",
  "Speaking sign language is much more than making motions with your hands. Did you know that sign language has grammar rules? If you break these rules, listeners might not understand what you’re saying.",
  "English speakers around the world generally understand each other. Dialects and accents differ, but the words are basically the same. However, this is not true with sign language.",
  "British Sign Language is very different from American Sign Language. In fact, ASL has more in common with French Sign Language than the British version.",
  "Grammar rules for sign language have to do with body positioning. How the speaker forms their eyebrows and eyes along with where they hold their hands is incredibly important when speaking sign language.",
  "Since people who are deaf can’t hear, clapping for a performance or event doesn’t make sense. Instead, the appropriate way to cheer in sign language is to wiggle or shake one’s hands in the air. This action shows someone the listener is happy and appreciated the show.",
]